version: "3"

services:
  nodejhonny:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejhonny
    container_name: node
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/home/node/app
    network_mode: bridge
